# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.8.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.8.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/monokrome/Projects/HAPEngine/hap

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/monokrome/Projects/HAPEngine/hap

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.8.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.8.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/monokrome/Projects/HAPEngine/hap/CMakeFiles /Users/monokrome/Projects/HAPEngine/hap/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/monokrome/Projects/HAPEngine/hap/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hap

# Build rule for target.
hap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hap
.PHONY : hap

# fast build rule for target.
hap/fast:
	$(MAKE) -f CMakeFiles/hap.dir/build.make CMakeFiles/hap.dir/build
.PHONY : hap/fast

#=============================================================================
# Target rules for targets named libhap

# Build rule for target.
libhap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libhap
.PHONY : libhap

# fast build rule for target.
libhap/fast:
	$(MAKE) -f CMakeFiles/libhap.dir/build.make CMakeFiles/libhap.dir/build
.PHONY : libhap/fast

src/cmds/hap.o: src/cmds/hap.c.o

.PHONY : src/cmds/hap.o

# target to build an object file
src/cmds/hap.c.o:
	$(MAKE) -f CMakeFiles/hap.dir/build.make CMakeFiles/hap.dir/src/cmds/hap.c.o
.PHONY : src/cmds/hap.c.o

src/cmds/hap.i: src/cmds/hap.c.i

.PHONY : src/cmds/hap.i

# target to preprocess a source file
src/cmds/hap.c.i:
	$(MAKE) -f CMakeFiles/hap.dir/build.make CMakeFiles/hap.dir/src/cmds/hap.c.i
.PHONY : src/cmds/hap.c.i

src/cmds/hap.s: src/cmds/hap.c.s

.PHONY : src/cmds/hap.s

# target to generate assembly for a file
src/cmds/hap.c.s:
	$(MAKE) -f CMakeFiles/hap.dir/build.make CMakeFiles/hap.dir/src/cmds/hap.c.s
.PHONY : src/cmds/hap.c.s

src/module.o: src/module.c.o

.PHONY : src/module.o

# target to build an object file
src/module.c.o:
	$(MAKE) -f CMakeFiles/libhap.dir/build.make CMakeFiles/libhap.dir/src/module.c.o
.PHONY : src/module.c.o

src/module.i: src/module.c.i

.PHONY : src/module.i

# target to preprocess a source file
src/module.c.i:
	$(MAKE) -f CMakeFiles/libhap.dir/build.make CMakeFiles/libhap.dir/src/module.c.i
.PHONY : src/module.c.i

src/module.s: src/module.c.s

.PHONY : src/module.s

# target to generate assembly for a file
src/module.c.s:
	$(MAKE) -f CMakeFiles/libhap.dir/build.make CMakeFiles/libhap.dir/src/module.c.s
.PHONY : src/module.c.s

src/timer.o: src/timer.c.o

.PHONY : src/timer.o

# target to build an object file
src/timer.c.o:
	$(MAKE) -f CMakeFiles/libhap.dir/build.make CMakeFiles/libhap.dir/src/timer.c.o
.PHONY : src/timer.c.o

src/timer.i: src/timer.c.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.c.i:
	$(MAKE) -f CMakeFiles/libhap.dir/build.make CMakeFiles/libhap.dir/src/timer.c.i
.PHONY : src/timer.c.i

src/timer.s: src/timer.c.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.c.s:
	$(MAKE) -f CMakeFiles/libhap.dir/build.make CMakeFiles/libhap.dir/src/timer.c.s
.PHONY : src/timer.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hap"
	@echo "... libhap"
	@echo "... src/cmds/hap.o"
	@echo "... src/cmds/hap.i"
	@echo "... src/cmds/hap.s"
	@echo "... src/module.o"
	@echo "... src/module.i"
	@echo "... src/module.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

